server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.12.112.235:3100/loki/api/v1/push # Tu IP de Loki en Docker

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: system-journal
        node: pm-132
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

  - job_name: pve-tasks
    static_configs:
    - targets:
        - localhost
      labels:
        job: pve-tasks
        node: pm-132
        __path__: /var/log/pve/tasks/**/*
