server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.12.112.235:3100/loki/api/v1/push # Tu IP de Loki en Docker

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: proxmox-system
        node: pm-132
        __path__: /var/log/syslog # Logs generales del sistema

  - job_name: pve-auth
    static_configs:
    - targets:
        - localhost
      labels:
        job: proxmox-auth
        node: pm-132
        __path__: /var/log/pveproxy/access.log # Accesos a la interfaz web

  - job_name: pve-cluster
    static_configs:
    - targets:
        - localhost
      labels:
        job: proxmox-cluster
        node: pm-132
        __path__: /var/log/pve/tasks/* # Historial de tareas (crear VM, backups, etc)