global:
  # Intervalo por defecto para raspar (scrape) métricas
  scrape_interval: 15s 

# Una lista de configuraciones de scraping para diferentes trabajos (jobs)
scrape_configs:
  # El job 'prometheus' monitorea la instancia local de Prometheus
  - job_name: 'prometheus'
    # Configuración estática para los objetivos (targets) a raspar
    static_configs:
      - targets: ['localhost:9090'] # El propio Prometheus se expone en 9090 dentro de su contenedor

# 2. NUEVO Job para monitorear Proxmox
  - job_name: 'proxmox'
    # Esta configuración permite a Prometheus contactar al Proxmox directamente
    # La IP es la de tu servidor Proxmox, y el puerto 9221 es el puerto por defecto del PVE Exporter.
    static_configs:
      - targets: ['10.12.112.233:9221']
    # Opcional: Si Proxmox no está en la misma zona horaria, puedes añadir una etiqueta
    # metrics_path: /metrics # Esta es la ruta por defecto, se puede omitir si es /metrics

# 3. NUEVO Job para monitorear el servidor Ubuntu con Node Exporter
  - job_name: 'ubuntu_node'
    # 'etiquetas' para identificar el origen de las métricas
    static_configs:
      - targets: ['10.12.112.236:9100'] # Usa la IP real de tu máquina Ubuntu
        labels:
          instance: ubuntu-server-01 # Nombre más amigable para Grafana