global:
  # Intervalo por defecto para raspar (scrape) métricas
  scrape_interval: 15s 

# Una lista de configuraciones de scraping para diferentes trabajos (jobs)
scrape_configs:

  - job_name: 'proxmox-nodes'
    static_configs:
      - targets:
        - '10.12.118.1:9100'
        - '10.12.118.2:9100'
        - '10.12.118.3:9100'